### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by 758334-tech** [UsboKirishima/vepar#1]
Hey I was just wondering how to use the script.

**Comment by UsboKirishima** [comment]
Hi! This software is still in development, please follow te process to keep updated on the state of it! I think maybe 2 weeks needed to release v1.0. 
If you want to try to run the dev version you need to understand the modules:
- Go to server dir and Run server, configuring .env with 'PASSWORD=', run commands: npm install, npm run start.

- Run test client: Go to server/ and run command npm run start-client , it's a simple testing client because dashboard still not exists.

- Run the zombie: go to zombie/ download with pip3 all the packages imported, copy and paste the .env file in the zombie dir, run python3 main.py

Sincerely,
usbo

**Comment by 758334-tech** [comment]
Ok Thanks
